# Site settings
title: Abhinav Kulkarni's blog
email: 
description: "Abhinav Kulkarni's blog"
baseurl: ""
url: "https://abhinavkulkarni.github.io/"

# Social links
twitter_username: kulkarniabhinav
github_username:  abhinavkulkarni

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
